java -jar ProteogenomicMapping-Git.jar -p "X:\owncloud\PeerJ-PeptideMapper\NewScenarios\LargePeptides\ChrY-50peptides.fa" -r "X:\owncloud\PeerJ-PeptideMapper\NewScenarios\LargePeptides\NucleotideY.fa" -n Standard -c genetic_code_tableNS.txt -o "X:\owncloud\PeerJ-PeptideMapper\NewScenarios\Outputs\LargePeptides\PGM\Output50.txt" -f "X:\owncloud\PeerJ-PeptideMapper\NewScenarios\Outputs\LargePeptides\PGM\Output50.fa" -3 "X:\owncloud\PeerJ-PeptideMapper\NewScenarios\Outputs\LargePeptides\PGM\Output50.gff3"
java -jar ProteogenomicMapping-Git.jar -p "X:\owncloud\PeerJ-PeptideMapper\NewScenarios\LargePeptides\ChrY-100peptides.fa" -r "X:\owncloud\PeerJ-PeptideMapper\NewScenarios\LargePeptides\NucleotideY.fa" -n Standard -c genetic_code_tableNS.txt -o "X:\ownCloud\PeerJ-PeptideMapper\NewScenarios\Outputs\LargePeptides\PGM\Output100.txt" -f "X:\ownCloud\PeerJ-PeptideMapper\NewScenarios\Outputs\LargePeptides\PGM\Output100.fa" -3 "X:\ownCloud\PeerJ-PeptideMapper\NewScenarios\Outputs\LargePeptides\PGM\Output100.gff3"
java -jar ProteogenomicMapping-Git.jar -p "X:\owncloud\PeerJ-PeptideMapper\NewScenarios\LargePeptides\ChrY-500peptides.fa" -r "X:\owncloud\PeerJ-PeptideMapper\NewScenarios\LargePeptides\NucleotideY.fa" -n Standard -c genetic_code_tableNS.txt -o "X:\ownCloud\PeerJ-PeptideMapper\NewScenarios\Outputs\LargePeptides\PGM\Outpu500t.txt" -f "X:\ownCloud\PeerJ-PeptideMapper\NewScenarios\Outputs\LargePeptides\PGM\Output500.fa" -3 "X:\ownCloud\PeerJ-PeptideMapper\NewScenarios\Outputs\LargePeptides\PGM\Output500.gff3"
java -jar ProteogenomicMapping-Git.jar -p "X:\owncloud\PeerJ-PeptideMapper\NewScenarios\LargePeptides\ChrY-1000peptides.fa" -r "X:\owncloud\PeerJ-PeptideMapper\NewScenarios\LargePeptides\NucleotideY.fa" -n Standard -c genetic_code_tableNS.txt -o "X:\ownCloud\PeerJ-PeptideMapper\NewScenarios\Outputs\LargePeptides\PGM\Output1000.txt" -f "X:\ownCloud\PeerJ-PeptideMapper\NewScenarios\Outputs\LargePeptides\PGM\Output1000.fa" -3 "X:\ownCloud\PeerJ-PeptideMapper\NewScenarios\Outputs\LargePeptides\PGM\Output1000.gff3"
java -jar ProteogenomicMapping-Git.jar -p "X:\owncloud\PeerJ-PeptideMapper\NewScenarios\LargePeptides\ChrY-5000peptides.fa" -r "X:\owncloud\PeerJ-PeptideMapper\NewScenarios\LargePeptides\NucleotideY.fa" -n Standard -c genetic_code_tableNS.txt -o "X:\owncloud\PeerJ-PeptideMapper\NewScenarios\Outputs\LargePeptides\PGM\Output5000.txt" -f "X:\owncloud\PeerJ-PeptideMapper\NewScenarios\Outputs\LargePeptides\PGM\Output5000.fa" -3 "X:\owncloud\PeerJ-PeptideMapper\NewScenarios\Outputs\LargePeptides\PGM\Output5000.gff3"
java -jar ProteogenomicMapping-Git.jar -p "X:\owncloud\PeerJ-PeptideMapper\NewScenarios\LargePeptides\ChrY-10000peptides.fa" -r "X:\owncloud\PeerJ-PeptideMapper\NewScenarios\LargePeptides\NucleotideY.fa" -n Standard -c genetic_code_tableNS.txt -o "X:\ownCloud\PeerJ-PeptideMapper\NewScenarios\Outputs\LargePeptides\PGM\Output10000.txt" -f "X:\ownCloud\PeerJ-PeptideMapper\NewScenarios\Outputs\LargePeptides\PGM\Output10000.fa" -3 "X:\ownCloud\PeerJ-PeptideMapper\NewScenarios\Outputs\LargePeptides\PGM\Output10000.gff3"
java -jar ProteogenomicMapping-Git.jar -p "X:\owncloud\PeerJ-PeptideMapper\NewScenarios\LargePeptides\ChrY-50000peptides.fa" -r "X:\owncloud\PeerJ-PeptideMapper\NewScenarios\LargePeptides\NucleotideY.fa" -n Standard -c genetic_code_tableNS.txt -o "X:\ownCloud\PeerJ-PeptideMapper\NewScenarios\Outputs\LargePeptides\PGM\Output50000.txt" -f "X:\ownCloud\PeerJ-PeptideMapper\NewScenarios\Outputs\LargePeptides\PGM\Output50000.fa" -3 "X:\ownCloud\PeerJ-PeptideMapper\NewScenarios\Outputs\LargePeptides\PGM\Output50000.gff3"
java -jar ProteogenomicMapping-Git.jar -p "X:\owncloud\PeerJ-PeptideMapper\NewScenarios\LargePeptides\ChrY-200000peptides.fa" -r "X:\owncloud\PeerJ-PeptideMapper\NewScenarios\LargePeptides\NucleotideY.fa" -n Standard -c genetic_code_tableNS.txt -o "X:\ownCloud\PeerJ-PeptideMapper\NewScenarios\Outputs\LargePeptides\PGM\Output200000.txt" -f "X:\ownCloud\PeerJ-PeptideMapper\NewScenarios\Outputs\LargePeptides\PGM\Output200000.fa" -3 "X:\ownCloud\PeerJ-PeptideMapper\NewScenarios\Outputs\LargePeptides\PGM\Output200000.gff3"


