java -jar ProteogenomicMapping-StandAlone.jar -p "X:\owncloud\PeerJ-PeptideMapper\Scenarios\Scenario1\scenario1queriesEnd.fa" -r "X:\owncloud\PeerJ-PeptideMapper\Scenarios\Scenario1\scenario1sequence6FT.fasta" -n Standard -c genetic_code_table.txt -o "X:\owncloud\PeerJ-PeptideMapper\Outputs\PGM-Current\Direct\Standalone\Sce1\scenario1qEnd.txt" -f "X:\owncloud\PeerJ-PeptideMapper\Outputs\PGM-Current\Direct\Standalone\Sce1\scenario1qEnd.fa" -3 "X:\owncloud\PeerJ-PeptideMapper\Outputs\PGM-Current\Direct\Standalone\Sce1\scenario1qEnd.gff3"
java -jar ProteogenomicMapping-StandAlone.jar -p "X:\owncloud\PeerJ-PeptideMapper\Scenarios\Scenario1\scenario1queriesFront.fa" -r "X:\owncloud\PeerJ-PeptideMapper\Scenarios\Scenario1\scenario1sequence6FT.fasta" -n Standard -c genetic_code_table.txt -o "X:\owncloud\PeerJ-PeptideMapper\Outputs\PGM-Current\Direct\Standalone\Sce1\scenario1qFront.txt" -f "X:\owncloud\PeerJ-PeptideMapper\Outputs\PGM-Current\Direct\Standalone\Sce1\scenario1qFront.fa" -3 "X:\owncloud\PeerJ-PeptideMapper\Outputs\PGM-Current\Direct\Standalone\Sce1\scenario1qFront.gff3"
java -jar ProteogenomicMapping-StandAlone.jar -p "X:\owncloud\PeerJ-PeptideMapper\Scenarios\Scenario1\scenario1queriesMiddle.fa" -r "X:\owncloud\PeerJ-PeptideMapper\Scenarios\Scenario1\scenario1sequence6FT.fasta" -n Standard -c genetic_code_table.txt -o "X:\owncloud\PeerJ-PeptideMapper\Outputs\PGM-Current\Direct\Standalone\Sce1\scenario1qMiddle.txt" -f "X:\owncloud\PeerJ-PeptideMapper\Outputs\PGM-Current\Direct\Standalone\Sce1\scenario1qMiddle.fa" -3 "X:\owncloud\PeerJ-PeptideMapper\Outputs\PGM-Current\Direct\Standalone\Sce1\scenario1qMiddle.gff3"

java -jar ProteogenomicMapping-StandAlone.jar -p "X:\owncloud\PeerJ-PeptideMapper\Scenarios\Scenario2\scenario2queries.fa" -r "X:\owncloud\PeerJ-PeptideMapper\Scenarios\Scenario2\scenario2sequence6FT.fasta" -n Standard -c genetic_code_table.txt -o "X:\owncloud\PeerJ-PeptideMapper\Outputs\PGM-Current\Direct\Standalone\Sce2\scenario2q.txt" -f "X:\owncloud\PeerJ-PeptideMapper\Outputs\PGM-Current\Direct\Standalone\Sce2\scenario2q.fa" -3 "X:\owncloud\PeerJ-PeptideMapper\Outputs\PGM-Current\Direct\Standalone\Sce2\scenario2q.gff3"

java -jar ProteogenomicMapping-StandAlone.jar -p "X:\owncloud\PeerJ-PeptideMapper\Scenarios\Scenario3\scenario3queries.fa" -r "X:\owncloud\PeerJ-PeptideMapper\Scenarios\Scenario3\scenario3sequence6FT.fasta" -n Standard -c genetic_code_table.txt -o "X:\owncloud\PeerJ-PeptideMapper\Outputs\PGM-Current\Direct\Standalone\Sce3\scenario3q.txt" -f "X:\owncloud\PeerJ-PeptideMapper\Outputs\PGM-Current\Direct\Standalone\Sce3\scenario3q.fa" -3 "X:\owncloud\PeerJ-PeptideMapper\Outputs\PGM-Current\Direct\Standalone\Sce3\scenario3q.gff3"

java -jar ProteogenomicMapping-StandAlone.jar -p "X:\owncloud\PeerJ-PeptideMapper\Scenarios\Scenario4\scenario4queriesFrontEnd.fa" -r "X:\owncloud\PeerJ-PeptideMapper\Scenarios\Scenario4\scenario4sequence6FT.fasta" -n Standard -c genetic_code_table.txt -o "X:\owncloud\PeerJ-PeptideMapper\Outputs\PGM-Current\Direct\Standalone\Sce4\scenario4qFrontEnd.txt" -f "X:\owncloud\PeerJ-PeptideMapper\Outputs\PGM-Current\Direct\Standalone\Sce4\scenario4qFrontEnd.fa" -3 "X:\owncloud\PeerJ-PeptideMapper\Outputs\PGM-Current\Direct\Standalone\Sce4\scenario4qFrontEnd.gff3"
java -jar ProteogenomicMapping-StandAlone.jar -p "X:\owncloud\PeerJ-PeptideMapper\Scenarios\Scenario4\scenario4queriesMiddle.fa" -r "X:\owncloud\PeerJ-PeptideMapper\Scenarios\Scenario4\scenario4sequence6FT.fasta" -n Standard -c genetic_code_table.txt -o "X:\owncloud\PeerJ-PeptideMapper\Outputs\PGM-Current\Direct\Standalone\Sce4\scenario4qMiddle.txt" -f "X:\owncloud\PeerJ-PeptideMapper\Outputs\PGM-Current\Direct\Standalone\Sce4\scenario4qMiddle.fa" -3 "X:\owncloud\PeerJ-PeptideMapper\Outputs\PGM-Current\Direct\Standalone\Sce4\scenario4qMiddle.gff3"

java -jar ProteogenomicMapping-StandAlone.jar -p "X:\owncloud\PeerJ-PeptideMapper\Scenarios\Scenario5\scenario5queries.fa" -r "X:\owncloud\PeerJ-PeptideMapper\Scenarios\Scenario5\scenario5sequenceTrans.fasta" -n Standard -c genetic_code_table.txt -o "X:\owncloud\PeerJ-PeptideMapper\Outputs\PGM-Current\Direct\Standalone\Sce5\scenario5q.txt" -f "X:\owncloud\PeerJ-PeptideMapper\Outputs\PGM-Current\Direct\Standalone\Sce5\scenario5q.fa" -3 "X:\owncloud\PeerJ-PeptideMapper\Outputs\PGM-Current\Direct\Standalone\Sce5\scenario5q.gff3"
